### ISSUE TITLE
Using orion-gridFS

### ISSUE THREAD

**Issue by bobattheoldstrawberryfarm** [brightbind/orion-gridFS#1]
Sorry to be so dense, I'm learning meteor and orion by following/modifying a blog example.
I can add orion-gridFS to my meteor application and upload an image of my logo from the admin/dictionary page.
orion.dictionary.addDefinition('logo', 'images', 
	orion.attribute('file', {
	    label: 'Site Logo',
	    optional: true
	})
);
How do I access the logo from the layout.html page?
{{ dict 'logo.url' 'http://i.imgur.com/6PeLvIG.png' }} does not seem to work.

Bob

**Comment by Weijtmans** [comment]
Dear Bob,

Please try: {{ dict 'images.logo.url' 'http://i.imgur.com/6PeLvIG.png' }}

Best,

Elgar
