### ISSUE TITLE
Add possibility to set max filesize

### ISSUE THREAD

**Issue by chompomonim** [brightbind/orion-gridFS#2]
For now I'm getting: `Error: FS.Collection insert: file does not pass collection filters` when uploading files bigger that 1Mb. I see that 1Mb is hardcoded in database. I'd like to have possibility to configure it.

**Comment by Ajaxsoap** [comment]
I have the same issue but the filesize is only 34kB excel file, yeah, how do we configure the filesize limitation or what kind of files are are supported to upload?
